language: node_js

node_js:
- 5.1
- 4

cache:
    directories:
        - node_modules
        
branches:
    only:
        - master
        - develop
        
install:
    - npm install
    
script:
    - npm run flow
    - npm run lint
    #- npm run test

notifications:
  email:
  - 'dmuelhau@hsr.ch'
  - 'marino.melchiori@gmail.com'